<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<AssemblyVersion>1.0.24.1</AssemblyVersion>
		<FileVersion>1.0.24.1</FileVersion>
		<Version>1.0.24</Version>
	</PropertyGroup>

	<ItemGroup Condition="Exists('..\\..\\lib\\DevExpress')">
		<Reference Include="DevExpress.Data.Desktop.v25.1">
			<HintPath>..\\..\\lib\\DevExpress\\DevExpress.Data.Desktop.v25.1.dll</HintPath>
			<Private>true</Private>
		</Reference>
		<Reference Include="DevExpress.XtraEditors.v25.1">
			<HintPath>..\\..\\lib\\DevExpress\\DevExpress.XtraEditors.v25.1.dll</HintPath>
			<Private>true</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
	</ItemGroup>

</Project>
